# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f4374f168f6e04a07f2de39301a192e0856ce9d84f017711d194eed8a788d6c65118dd576833435ce52653c3e057f4321e2c059c87ada8ce740e79ee51d037a

test:
  secret_key_base: 647d83981ffbdd2ba5471ffce49753649f48df0f8d9a1adc07cc05b194c7a31e520f241f26ca3b114dd2bb793e065b58c735aea6f607d43aa3d430c9dc0f0fd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
